package com.example.jdbc.aula1902.controller;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbc.aula1902.entities.Category;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/test")
public class JDBCController {

  public List<Category> list = new ArrayList<Category>();

  @GetMapping
  public ResponseEntity<String> test() {

    String mensagem;

    try {
      Class.forName("org.h2.Driver");
      mensagem = "<h1>Driver carregado com sucesso!</h1>";

      String url = "jdbc:h2:mem:testdb";
      String user = "sa";
      String pwd = "";

      Connection con = DriverManager.getConnection(url, user, pwd);
      mensagem += "<h1>Conexão estabelecida!</h1>";

      Statement stm = con.createStatement();
      mensagem += "<h1>Statement criado com sucesso!</h1>";


      stm.execute("drop table IF EXISTS tb_category");

      mensagem += "<h1>DROP!</h1>";

      stm.execute("create table tb_category ("+
                  "id int8 generated by default as identity,"+
                  " created_at TIMESTAMP WITHOUT TIME ZONE,"+
                  " name varchar(255),"+
                  " primary key (id))");

      stm.execute("INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW())");
      stm.execute("INSERT INTO tb_category (name, created_At) VALUES ('Eletrônicos', NOW())");
      stm.execute("INSERT INTO tb_category (name, created_At) VALUES ('Computadores', NOW());");
      mensagem += "<h1>Insert Table OK!!!!!</h1>";
      
      ResultSet rs = stm.executeQuery("SELECT * FROM TB_CATEGORY");
      
      while(rs.next()){
        Category c = new Category();
        c.setId(rs.getInt("id"));
        c.setName(rs.getString("name"));

        list.add(c);
      }

    } 
    catch (ClassNotFoundException e) {
      mensagem = "<h1>Erro ao carregar o Driver!</h1>";
      e.printStackTrace();
    }
    catch (SQLException e) {
      mensagem = "<h1>Erro ao conectar com o banco!</h1>";
      e.printStackTrace();
    }
    
    return ResponseEntity.ok().body(mensagem);
  }  
}
